services:
  jenkins:
#    image: jenkins/jenkins:lts
    privileged: true
    user: root
    build:
      context: ./master
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home_summit:/var/jenkins_home
      - ./casc:/var/jenkins_home/casc_configs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=unix:///var/run/docker.sock
volumes:
  jenkins_home_summit: