jenkins:
  systemMessage: "Jenkins configured using JCasC"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  # Example global tool configuration
  globalNodeProperties:
    - envVars:
        env:
          - key: EXAMPLE_VARIABLE
            value: example_value

  # Jenkins URL configuration
  locationConfiguration:
    url: http://localhost:8080/

  # Number of executors on master
  numExecutors: 2

# Example job configurations
jobs:
  - script: >
      folder('CI') {
        description('Continuous Integration Jobs')
      }
      pipelineJob('CI/example-pipeline') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                stages {
                  stage('Example') {
                    steps {
                      echo 'Hello World'
                    }
                  }
                }
              }
            ''')
            sandbox(true)
          }
        }
      }

# Configuration for plugins
tool:
  git:
    installations:
      - name: git
        home: git
